name: tsdb-health-plugin-dev
services:
  timescaledb:
    image: timescale/timescaledb:2.25.2-pg16
    environment: { POSTGRES_DB: demo, POSTGRES_USER: postgres, POSTGRES_PASSWORD: postgres }
    volumes: [ "./sql:/docker-entrypoint-initdb.d:ro" ]
    healthcheck: { test: ["CMD-SHELL","pg_isready -U postgres -d demo"], interval: 5s, timeout: 5s, retries: 20 }
  grafana:
    image: grafana/grafana:11.3.0
    ports: [ "3001:3000" ]
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=custom-timescale-health-panel
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ../dist:/var/lib/grafana/plugins/custom-timescale-health-panel:ro
      - ./provisioning:/etc/grafana/provisioning:ro
      - ./dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      timescaledb: { condition: service_healthy }
